### ISSUE TITLE
Please set a recognisible User-Agent

### ISSUE THREAD

**Issue by ties** [bgpsecurity/rpstir2#14]
Hi,

When I was analysing RRDP HTTP logfiles today I noticed requests from `Go-http-client/2.0`. We're assuming that this is from rpstir2.

As a repository operator it would help me if rpstir2 set a recognizable user-agent so I could estimate the usage of each RP implementation.

**Comment by cpusoft** [comment]
The keyword RPSTIR2 has been added to User-Agent:
"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36 RPSTIR2"

**Comment by ties** [comment]
Thanks!
